title:              Craftstoff
email:              marke@craftstoff.com
description:        registered brand for licensing
author:             Start Bootstrap
baseurl:            ""




# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

